### ISSUE TITLE
Cant install cs.p5migrator

### ISSUE THREAD

**Issue by rafaeltcc** [codesyntax/cs.p5migrator#1]
Hi,
I am following the instructions but I get:

error: Could not find suitable distribution for Requirement.parse('cs.p5migrator')

Also trying to install via buildout:

Couldn't find index page for 'cs.p5migrator' 

Do I need to add a repository? Do I need to download it manually? I saw no instructions to use the dev eggs folders.

Thanks,

Rafael

**Comment by erral** [comment]
For now it's a work in progress, so there is no release on PyPI. You need to add it to the [sources] block of your buildout and to auto-checkout too.

The 3rd and 4th step of the instructions don't work too, we are working on it.

**Comment by libargutxi** [comment]
For now, in order for the 3rd and 4th steps work you must change the
parameters in the import.cfg file.

2016-06-08 9:10 GMT+02:00 Mikel Larreategi <notifications@github.com>:

> For now it's a work in progress, so there is no release on PyPI. You need
> to add it to the [sources] block of your buildout and to auto-checkout too.
>
> The 3rd and 4th step of the instructions don't work too, we are working on
> it.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/codesyntax/cs.p5migrator/issues/1#issuecomment-224507501>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ABfQignZewms9vBtMtof63eLcUWZSDHKks5qJmrTgaJpZM4IwGBY>
> .
>



-- 
Lur Ibargutxi
libargutxi@codesyntax.com

**Comment by rafaeltcc** [comment]
Thanks a lot. I will try...



2016-06-08 4:32 GMT-03:00 Lur Ibargutxi <notifications@github.com>:
